/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClubRouteImport } from './routes/club'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminClubsRouteImport } from './routes/admin.clubs'
import { Route as AdminConnectionsRouteImport } from './routes/admin.connections'
import { Route as AdminConversationsRouteImport } from './routes/admin.conversations'
import { Route as AdminFounderClubsRouteImport } from './routes/admin.founder-clubs'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminOwnerStatusRouteImport } from './routes/admin.owner-status'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTrialsRouteImport } from './routes/admin.trials'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as ClubIndexRouteImport } from './routes/club.index'
import { Route as ClubApplicationsRouteImport } from './routes/club.applications'
import { Route as ClubFindPlayersRouteImport } from './routes/club.find-players'
import { Route as ClubProfileRouteImport } from './routes/club.profile'
import { Route as ClubSavedPlayersRouteImport } from './routes/club.saved-players'
import { Route as ClubSettingsRouteImport } from './routes/club.settings'
import { Route as ClubShortlistRouteImport } from './routes/club.shortlist'
import { Route as ClubTrialsRouteImport } from './routes/club.trials'
import { Route as ClubsSlugRouteImport } from './routes/clubs.$slug'
import { Route as JoinIndexRouteImport } from './routes/join.index'
import { Route as JoinClubRouteImport } from './routes/join.club'
import { Route as JoinPlayerRouteImport } from './routes/join.player'
import { Route as PlayerIndexRouteImport } from './routes/player.index'
import { Route as PlayerApplicationsRouteImport } from './routes/player.applications'
import { Route as PlayerFindClubsRouteImport } from './routes/player.find-clubs'
import { Route as PlayerFindPlayersRouteImport } from './routes/player.find-players'
import { Route as PlayerProfileRouteImport } from './routes/player.profile'
import { Route as PlayerSavedRouteImport } from './routes/player.saved'
import { Route as PlayerSettingsRouteImport } from './routes/player.settings'
import { Route as PlayersSlugRouteImport } from './routes/players.$slug'
import { Route as VacanciesSlugRouteImport } from './routes/vacancies.$slug'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersProfileIdRouteImport } from './routes/admin.users.$profileId'
import { Route as ClubClubsClubIdRouteImport } from './routes/club.clubs.$clubId'
import { Route as ClubMessagesIndexRouteImport } from './routes/club.messages.index'
import { Route as ClubMessagesConversationIdRouteImport } from './routes/club.messages.$conversationId'
import { Route as ClubPlayersPlayerIdRouteImport } from './routes/club.players.$playerId'
import { Route as ClubVacanciesIndexRouteImport } from './routes/club.vacancies.index'
import { Route as ClubVacanciesNewRouteImport } from './routes/club.vacancies.new'
import { Route as PlayerClubsClubIdRouteImport } from './routes/player.clubs.$clubId'
import { Route as PlayerMessagesIndexRouteImport } from './routes/player.messages.index'
import { Route as PlayerMessagesConversationIdRouteImport } from './routes/player.messages.$conversationId'
import { Route as PlayerPlayersPlayerIdRouteImport } from './routes/player.players.$playerId'
import { Route as PlayerTrialsIndexRouteImport } from './routes/player.trials.index'
import { Route as PlayerTrialsInviteIdRouteImport } from './routes/player.trials.$inviteId'
import { Route as ClubVacanciesVacancyIdEditRouteImport } from './routes/club.vacancies.$vacancyId.edit'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicShareImageKindSlugRouteImport } from './routes/api/public/share-image.$kind.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClubsRoute = AdminClubsRouteImport.update({
  id: '/admin/clubs',
  path: '/admin/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnectionsRoute = AdminConnectionsRouteImport.update({
  id: '/admin/connections',
  path: '/admin/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/admin/conversations',
  path: '/admin/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFounderClubsRoute = AdminFounderClubsRouteImport.update({
  id: '/admin/founder-clubs',
  path: '/admin/founder-clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/admin/history',
  path: '/admin/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOwnerStatusRoute = AdminOwnerStatusRouteImport.update({
  id: '/admin/owner-status',
  path: '/admin/owner-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/admin/players',
  path: '/admin/players',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrialsRoute = AdminTrialsRouteImport.update({
  id: '/admin/trials',
  path: '/admin/trials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubApplicationsRoute = ClubApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => ClubRoute,
} as any)
const ClubFindPlayersRoute = ClubFindPlayersRouteImport.update({
  id: '/find-players',
  path: '/find-players',
  getParentRoute: () => ClubRoute,
} as any)
const ClubProfileRoute = ClubProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClubRoute,
} as any)
const ClubSavedPlayersRoute = ClubSavedPlayersRouteImport.update({
  id: '/saved-players',
  path: '/saved-players',
  getParentRoute: () => ClubRoute,
} as any)
const ClubSettingsRoute = ClubSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClubRoute,
} as any)
const ClubShortlistRoute = ClubShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => ClubRoute,
} as any)
const ClubTrialsRoute = ClubTrialsRouteImport.update({
  id: '/trials',
  path: '/trials',
  getParentRoute: () => ClubRoute,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/clubs/$slug',
  path: '/clubs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinClubRoute = JoinClubRouteImport.update({
  id: '/join/club',
  path: '/join/club',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinPlayerRoute = JoinPlayerRouteImport.update({
  id: '/join/player',
  path: '/join/player',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerApplicationsRoute = PlayerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerFindClubsRoute = PlayerFindClubsRouteImport.update({
  id: '/find-clubs',
  path: '/find-clubs',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerFindPlayersRoute = PlayerFindPlayersRouteImport.update({
  id: '/find-players',
  path: '/find-players',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerProfileRoute = PlayerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerSavedRoute = PlayerSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerSettingsRoute = PlayerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayersSlugRoute = PlayersSlugRouteImport.update({
  id: '/players/$slug',
  path: '/players/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesSlugRoute = VacanciesSlugRouteImport.update({
  id: '/vacancies/$slug',
  path: '/vacancies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersProfileIdRoute = AdminUsersProfileIdRouteImport.update({
  id: '/admin/users/$profileId',
  path: '/admin/users/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubClubsClubIdRoute = ClubClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => ClubRoute,
} as any)
const ClubMessagesIndexRoute = ClubMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubMessagesConversationIdRoute =
  ClubMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => ClubRoute,
  } as any)
const ClubPlayersPlayerIdRoute = ClubPlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => ClubRoute,
} as any)
const ClubVacanciesIndexRoute = ClubVacanciesIndexRouteImport.update({
  id: '/vacancies/',
  path: '/vacancies/',
  getParentRoute: () => ClubRoute,
} as any)
const ClubVacanciesNewRoute = ClubVacanciesNewRouteImport.update({
  id: '/vacancies/new',
  path: '/vacancies/new',
  getParentRoute: () => ClubRoute,
} as any)
const PlayerClubsClubIdRoute = PlayerClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerMessagesIndexRoute = PlayerMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerMessagesConversationIdRoute =
  PlayerMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => PlayerRoute,
  } as any)
const PlayerPlayersPlayerIdRoute = PlayerPlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerTrialsIndexRoute = PlayerTrialsIndexRouteImport.update({
  id: '/trials/',
  path: '/trials/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerTrialsInviteIdRoute = PlayerTrialsInviteIdRouteImport.update({
  id: '/trials/$inviteId',
  path: '/trials/$inviteId',
  getParentRoute: () => PlayerRoute,
} as any)
const ClubVacanciesVacancyIdEditRoute =
  ClubVacanciesVacancyIdEditRouteImport.update({
    id: '/vacancies/$vacancyId/edit',
    path: '/vacancies/$vacancyId/edit',
    getParentRoute: () => ClubRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShareImageKindSlugRoute =
  ApiPublicShareImageKindSlugRouteImport.update({
    id: '/api/public/share-image/$kind/$slug',
    path: '/api/public/share-image/$kind/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/admin/clubs': typeof AdminClubsRoute
  '/admin/connections': typeof AdminConnectionsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/founder-clubs': typeof AdminFounderClubsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/owner-status': typeof AdminOwnerStatusRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trials': typeof AdminTrialsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/club/applications': typeof ClubApplicationsRoute
  '/club/find-players': typeof ClubFindPlayersRoute
  '/club/profile': typeof ClubProfileRoute
  '/club/saved-players': typeof ClubSavedPlayersRoute
  '/club/settings': typeof ClubSettingsRoute
  '/club/shortlist': typeof ClubShortlistRoute
  '/club/trials': typeof ClubTrialsRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/join/club': typeof JoinClubRoute
  '/join/player': typeof JoinPlayerRoute
  '/player/applications': typeof PlayerApplicationsRoute
  '/player/find-clubs': typeof PlayerFindClubsRoute
  '/player/find-players': typeof PlayerFindPlayersRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/saved': typeof PlayerSavedRoute
  '/player/settings': typeof PlayerSettingsRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/vacancies/$slug': typeof VacanciesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/club/': typeof ClubIndexRoute
  '/join/': typeof JoinIndexRoute
  '/player/': typeof PlayerIndexRoute
  '/admin/users/$profileId': typeof AdminUsersProfileIdRoute
  '/club/clubs/$clubId': typeof ClubClubsClubIdRoute
  '/club/messages/$conversationId': typeof ClubMessagesConversationIdRoute
  '/club/players/$playerId': typeof ClubPlayersPlayerIdRoute
  '/club/vacancies/new': typeof ClubVacanciesNewRoute
  '/player/clubs/$clubId': typeof PlayerClubsClubIdRoute
  '/player/messages/$conversationId': typeof PlayerMessagesConversationIdRoute
  '/player/players/$playerId': typeof PlayerPlayersPlayerIdRoute
  '/player/trials/$inviteId': typeof PlayerTrialsInviteIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/club/messages/': typeof ClubMessagesIndexRoute
  '/club/vacancies/': typeof ClubVacanciesIndexRoute
  '/player/messages/': typeof PlayerMessagesIndexRoute
  '/player/trials/': typeof PlayerTrialsIndexRoute
  '/club/vacancies/$vacancyId/edit': typeof ClubVacanciesVacancyIdEditRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/share-image/$kind/$slug': typeof ApiPublicShareImageKindSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/admin/clubs': typeof AdminClubsRoute
  '/admin/connections': typeof AdminConnectionsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/founder-clubs': typeof AdminFounderClubsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/owner-status': typeof AdminOwnerStatusRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trials': typeof AdminTrialsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/club/applications': typeof ClubApplicationsRoute
  '/club/find-players': typeof ClubFindPlayersRoute
  '/club/profile': typeof ClubProfileRoute
  '/club/saved-players': typeof ClubSavedPlayersRoute
  '/club/settings': typeof ClubSettingsRoute
  '/club/shortlist': typeof ClubShortlistRoute
  '/club/trials': typeof ClubTrialsRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/join/club': typeof JoinClubRoute
  '/join/player': typeof JoinPlayerRoute
  '/player/applications': typeof PlayerApplicationsRoute
  '/player/find-clubs': typeof PlayerFindClubsRoute
  '/player/find-players': typeof PlayerFindPlayersRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/saved': typeof PlayerSavedRoute
  '/player/settings': typeof PlayerSettingsRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/vacancies/$slug': typeof VacanciesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/club': typeof ClubIndexRoute
  '/join': typeof JoinIndexRoute
  '/player': typeof PlayerIndexRoute
  '/admin/users/$profileId': typeof AdminUsersProfileIdRoute
  '/club/clubs/$clubId': typeof ClubClubsClubIdRoute
  '/club/messages/$conversationId': typeof ClubMessagesConversationIdRoute
  '/club/players/$playerId': typeof ClubPlayersPlayerIdRoute
  '/club/vacancies/new': typeof ClubVacanciesNewRoute
  '/player/clubs/$clubId': typeof PlayerClubsClubIdRoute
  '/player/messages/$conversationId': typeof PlayerMessagesConversationIdRoute
  '/player/players/$playerId': typeof PlayerPlayersPlayerIdRoute
  '/player/trials/$inviteId': typeof PlayerTrialsInviteIdRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/club/messages': typeof ClubMessagesIndexRoute
  '/club/vacancies': typeof ClubVacanciesIndexRoute
  '/player/messages': typeof PlayerMessagesIndexRoute
  '/player/trials': typeof PlayerTrialsIndexRoute
  '/club/vacancies/$vacancyId/edit': typeof ClubVacanciesVacancyIdEditRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/share-image/$kind/$slug': typeof ApiPublicShareImageKindSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/admin/clubs': typeof AdminClubsRoute
  '/admin/connections': typeof AdminConnectionsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/founder-clubs': typeof AdminFounderClubsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/owner-status': typeof AdminOwnerStatusRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trials': typeof AdminTrialsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/club/applications': typeof ClubApplicationsRoute
  '/club/find-players': typeof ClubFindPlayersRoute
  '/club/profile': typeof ClubProfileRoute
  '/club/saved-players': typeof ClubSavedPlayersRoute
  '/club/settings': typeof ClubSettingsRoute
  '/club/shortlist': typeof ClubShortlistRoute
  '/club/trials': typeof ClubTrialsRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/join/club': typeof JoinClubRoute
  '/join/player': typeof JoinPlayerRoute
  '/player/applications': typeof PlayerApplicationsRoute
  '/player/find-clubs': typeof PlayerFindClubsRoute
  '/player/find-players': typeof PlayerFindPlayersRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/saved': typeof PlayerSavedRoute
  '/player/settings': typeof PlayerSettingsRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/vacancies/$slug': typeof VacanciesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/club/': typeof ClubIndexRoute
  '/join/': typeof JoinIndexRoute
  '/player/': typeof PlayerIndexRoute
  '/admin/users/$profileId': typeof AdminUsersProfileIdRoute
  '/club/clubs/$clubId': typeof ClubClubsClubIdRoute
  '/club/messages/$conversationId': typeof ClubMessagesConversationIdRoute
  '/club/players/$playerId': typeof ClubPlayersPlayerIdRoute
  '/club/vacancies/new': typeof ClubVacanciesNewRoute
  '/player/clubs/$clubId': typeof PlayerClubsClubIdRoute
  '/player/messages/$conversationId': typeof PlayerMessagesConversationIdRoute
  '/player/players/$playerId': typeof PlayerPlayersPlayerIdRoute
  '/player/trials/$inviteId': typeof PlayerTrialsInviteIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/club/messages/': typeof ClubMessagesIndexRoute
  '/club/vacancies/': typeof ClubVacanciesIndexRoute
  '/player/messages/': typeof PlayerMessagesIndexRoute
  '/player/trials/': typeof PlayerTrialsIndexRoute
  '/club/vacancies/$vacancyId/edit': typeof ClubVacanciesVacancyIdEditRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/share-image/$kind/$slug': typeof ApiPublicShareImageKindSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/club'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/player'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/admin/clubs'
    | '/admin/connections'
    | '/admin/conversations'
    | '/admin/founder-clubs'
    | '/admin/history'
    | '/admin/login'
    | '/admin/owner-status'
    | '/admin/players'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/trials'
    | '/admin/verification'
    | '/club/applications'
    | '/club/find-players'
    | '/club/profile'
    | '/club/saved-players'
    | '/club/settings'
    | '/club/shortlist'
    | '/club/trials'
    | '/clubs/$slug'
    | '/join/club'
    | '/join/player'
    | '/player/applications'
    | '/player/find-clubs'
    | '/player/find-players'
    | '/player/profile'
    | '/player/saved'
    | '/player/settings'
    | '/players/$slug'
    | '/vacancies/$slug'
    | '/admin/'
    | '/club/'
    | '/join/'
    | '/player/'
    | '/admin/users/$profileId'
    | '/club/clubs/$clubId'
    | '/club/messages/$conversationId'
    | '/club/players/$playerId'
    | '/club/vacancies/new'
    | '/player/clubs/$clubId'
    | '/player/messages/$conversationId'
    | '/player/players/$playerId'
    | '/player/trials/$inviteId'
    | '/admin/users/'
    | '/club/messages/'
    | '/club/vacancies/'
    | '/player/messages/'
    | '/player/trials/'
    | '/club/vacancies/$vacancyId/edit'
    | '/lovable/email/transactional/preview'
    | '/api/public/share-image/$kind/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/admin/clubs'
    | '/admin/connections'
    | '/admin/conversations'
    | '/admin/founder-clubs'
    | '/admin/history'
    | '/admin/login'
    | '/admin/owner-status'
    | '/admin/players'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/trials'
    | '/admin/verification'
    | '/club/applications'
    | '/club/find-players'
    | '/club/profile'
    | '/club/saved-players'
    | '/club/settings'
    | '/club/shortlist'
    | '/club/trials'
    | '/clubs/$slug'
    | '/join/club'
    | '/join/player'
    | '/player/applications'
    | '/player/find-clubs'
    | '/player/find-players'
    | '/player/profile'
    | '/player/saved'
    | '/player/settings'
    | '/players/$slug'
    | '/vacancies/$slug'
    | '/admin'
    | '/club'
    | '/join'
    | '/player'
    | '/admin/users/$profileId'
    | '/club/clubs/$clubId'
    | '/club/messages/$conversationId'
    | '/club/players/$playerId'
    | '/club/vacancies/new'
    | '/player/clubs/$clubId'
    | '/player/messages/$conversationId'
    | '/player/players/$playerId'
    | '/player/trials/$inviteId'
    | '/admin/users'
    | '/club/messages'
    | '/club/vacancies'
    | '/player/messages'
    | '/player/trials'
    | '/club/vacancies/$vacancyId/edit'
    | '/lovable/email/transactional/preview'
    | '/api/public/share-image/$kind/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/club'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/player'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/admin/clubs'
    | '/admin/connections'
    | '/admin/conversations'
    | '/admin/founder-clubs'
    | '/admin/history'
    | '/admin/login'
    | '/admin/owner-status'
    | '/admin/players'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/trials'
    | '/admin/verification'
    | '/club/applications'
    | '/club/find-players'
    | '/club/profile'
    | '/club/saved-players'
    | '/club/settings'
    | '/club/shortlist'
    | '/club/trials'
    | '/clubs/$slug'
    | '/join/club'
    | '/join/player'
    | '/player/applications'
    | '/player/find-clubs'
    | '/player/find-players'
    | '/player/profile'
    | '/player/saved'
    | '/player/settings'
    | '/players/$slug'
    | '/vacancies/$slug'
    | '/admin/'
    | '/club/'
    | '/join/'
    | '/player/'
    | '/admin/users/$profileId'
    | '/club/clubs/$clubId'
    | '/club/messages/$conversationId'
    | '/club/players/$playerId'
    | '/club/vacancies/new'
    | '/player/clubs/$clubId'
    | '/player/messages/$conversationId'
    | '/player/players/$playerId'
    | '/player/trials/$inviteId'
    | '/admin/users/'
    | '/club/messages/'
    | '/club/vacancies/'
    | '/player/messages/'
    | '/player/trials/'
    | '/club/vacancies/$vacancyId/edit'
    | '/lovable/email/transactional/preview'
    | '/api/public/share-image/$kind/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClubRoute: typeof ClubRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PlayerRoute: typeof PlayerRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminClubsRoute: typeof AdminClubsRoute
  AdminConnectionsRoute: typeof AdminConnectionsRoute
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminFounderClubsRoute: typeof AdminFounderClubsRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOwnerStatusRoute: typeof AdminOwnerStatusRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrialsRoute: typeof AdminTrialsRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  ClubsSlugRoute: typeof ClubsSlugRoute
  JoinClubRoute: typeof JoinClubRoute
  JoinPlayerRoute: typeof JoinPlayerRoute
  PlayersSlugRoute: typeof PlayersSlugRoute
  VacanciesSlugRoute: typeof VacanciesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JoinIndexRoute: typeof JoinIndexRoute
  AdminUsersProfileIdRoute: typeof AdminUsersProfileIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  ApiPublicShareImageKindSlugRoute: typeof ApiPublicShareImageKindSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clubs': {
      id: '/admin/clubs'
      path: '/admin/clubs'
      fullPath: '/admin/clubs'
      preLoaderRoute: typeof AdminClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/connections': {
      id: '/admin/connections'
      path: '/admin/connections'
      fullPath: '/admin/connections'
      preLoaderRoute: typeof AdminConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/admin/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/founder-clubs': {
      id: '/admin/founder-clubs'
      path: '/admin/founder-clubs'
      fullPath: '/admin/founder-clubs'
      preLoaderRoute: typeof AdminFounderClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/admin/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/owner-status': {
      id: '/admin/owner-status'
      path: '/admin/owner-status'
      fullPath: '/admin/owner-status'
      preLoaderRoute: typeof AdminOwnerStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/admin/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trials': {
      id: '/admin/trials'
      path: '/admin/trials'
      fullPath: '/admin/trials'
      preLoaderRoute: typeof AdminTrialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/applications': {
      id: '/club/applications'
      path: '/applications'
      fullPath: '/club/applications'
      preLoaderRoute: typeof ClubApplicationsRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/find-players': {
      id: '/club/find-players'
      path: '/find-players'
      fullPath: '/club/find-players'
      preLoaderRoute: typeof ClubFindPlayersRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/profile': {
      id: '/club/profile'
      path: '/profile'
      fullPath: '/club/profile'
      preLoaderRoute: typeof ClubProfileRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/saved-players': {
      id: '/club/saved-players'
      path: '/saved-players'
      fullPath: '/club/saved-players'
      preLoaderRoute: typeof ClubSavedPlayersRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/settings': {
      id: '/club/settings'
      path: '/settings'
      fullPath: '/club/settings'
      preLoaderRoute: typeof ClubSettingsRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/shortlist': {
      id: '/club/shortlist'
      path: '/shortlist'
      fullPath: '/club/shortlist'
      preLoaderRoute: typeof ClubShortlistRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/trials': {
      id: '/club/trials'
      path: '/trials'
      fullPath: '/club/trials'
      preLoaderRoute: typeof ClubTrialsRouteImport
      parentRoute: typeof ClubRoute
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/clubs/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/club': {
      id: '/join/club'
      path: '/join/club'
      fullPath: '/join/club'
      preLoaderRoute: typeof JoinClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/player': {
      id: '/join/player'
      path: '/join/player'
      fullPath: '/join/player'
      preLoaderRoute: typeof JoinPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/applications': {
      id: '/player/applications'
      path: '/applications'
      fullPath: '/player/applications'
      preLoaderRoute: typeof PlayerApplicationsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/find-clubs': {
      id: '/player/find-clubs'
      path: '/find-clubs'
      fullPath: '/player/find-clubs'
      preLoaderRoute: typeof PlayerFindClubsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/find-players': {
      id: '/player/find-players'
      path: '/find-players'
      fullPath: '/player/find-players'
      preLoaderRoute: typeof PlayerFindPlayersRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/profile': {
      id: '/player/profile'
      path: '/profile'
      fullPath: '/player/profile'
      preLoaderRoute: typeof PlayerProfileRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/saved': {
      id: '/player/saved'
      path: '/saved'
      fullPath: '/player/saved'
      preLoaderRoute: typeof PlayerSavedRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/settings': {
      id: '/player/settings'
      path: '/settings'
      fullPath: '/player/settings'
      preLoaderRoute: typeof PlayerSettingsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/players/$slug': {
      id: '/players/$slug'
      path: '/players/$slug'
      fullPath: '/players/$slug'
      preLoaderRoute: typeof PlayersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies/$slug': {
      id: '/vacancies/$slug'
      path: '/vacancies/$slug'
      fullPath: '/vacancies/$slug'
      preLoaderRoute: typeof VacanciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$profileId': {
      id: '/admin/users/$profileId'
      path: '/admin/users/$profileId'
      fullPath: '/admin/users/$profileId'
      preLoaderRoute: typeof AdminUsersProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/clubs/$clubId': {
      id: '/club/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/club/clubs/$clubId'
      preLoaderRoute: typeof ClubClubsClubIdRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/messages/': {
      id: '/club/messages/'
      path: '/messages'
      fullPath: '/club/messages/'
      preLoaderRoute: typeof ClubMessagesIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/messages/$conversationId': {
      id: '/club/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/club/messages/$conversationId'
      preLoaderRoute: typeof ClubMessagesConversationIdRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/players/$playerId': {
      id: '/club/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/club/players/$playerId'
      preLoaderRoute: typeof ClubPlayersPlayerIdRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/vacancies/': {
      id: '/club/vacancies/'
      path: '/vacancies'
      fullPath: '/club/vacancies/'
      preLoaderRoute: typeof ClubVacanciesIndexRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/vacancies/new': {
      id: '/club/vacancies/new'
      path: '/vacancies/new'
      fullPath: '/club/vacancies/new'
      preLoaderRoute: typeof ClubVacanciesNewRouteImport
      parentRoute: typeof ClubRoute
    }
    '/player/clubs/$clubId': {
      id: '/player/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/player/clubs/$clubId'
      preLoaderRoute: typeof PlayerClubsClubIdRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/messages/': {
      id: '/player/messages/'
      path: '/messages'
      fullPath: '/player/messages/'
      preLoaderRoute: typeof PlayerMessagesIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/messages/$conversationId': {
      id: '/player/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/player/messages/$conversationId'
      preLoaderRoute: typeof PlayerMessagesConversationIdRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/players/$playerId': {
      id: '/player/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/player/players/$playerId'
      preLoaderRoute: typeof PlayerPlayersPlayerIdRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/trials/': {
      id: '/player/trials/'
      path: '/trials'
      fullPath: '/player/trials/'
      preLoaderRoute: typeof PlayerTrialsIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/trials/$inviteId': {
      id: '/player/trials/$inviteId'
      path: '/trials/$inviteId'
      fullPath: '/player/trials/$inviteId'
      preLoaderRoute: typeof PlayerTrialsInviteIdRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/club/vacancies/$vacancyId/edit': {
      id: '/club/vacancies/$vacancyId/edit'
      path: '/vacancies/$vacancyId/edit'
      fullPath: '/club/vacancies/$vacancyId/edit'
      preLoaderRoute: typeof ClubVacanciesVacancyIdEditRouteImport
      parentRoute: typeof ClubRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/share-image/$kind/$slug': {
      id: '/api/public/share-image/$kind/$slug'
      path: '/api/public/share-image/$kind/$slug'
      fullPath: '/api/public/share-image/$kind/$slug'
      preLoaderRoute: typeof ApiPublicShareImageKindSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClubRouteChildren {
  ClubApplicationsRoute: typeof ClubApplicationsRoute
  ClubFindPlayersRoute: typeof ClubFindPlayersRoute
  ClubProfileRoute: typeof ClubProfileRoute
  ClubSavedPlayersRoute: typeof ClubSavedPlayersRoute
  ClubSettingsRoute: typeof ClubSettingsRoute
  ClubShortlistRoute: typeof ClubShortlistRoute
  ClubTrialsRoute: typeof ClubTrialsRoute
  ClubIndexRoute: typeof ClubIndexRoute
  ClubClubsClubIdRoute: typeof ClubClubsClubIdRoute
  ClubMessagesConversationIdRoute: typeof ClubMessagesConversationIdRoute
  ClubPlayersPlayerIdRoute: typeof ClubPlayersPlayerIdRoute
  ClubVacanciesNewRoute: typeof ClubVacanciesNewRoute
  ClubMessagesIndexRoute: typeof ClubMessagesIndexRoute
  ClubVacanciesIndexRoute: typeof ClubVacanciesIndexRoute
  ClubVacanciesVacancyIdEditRoute: typeof ClubVacanciesVacancyIdEditRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubApplicationsRoute: ClubApplicationsRoute,
  ClubFindPlayersRoute: ClubFindPlayersRoute,
  ClubProfileRoute: ClubProfileRoute,
  ClubSavedPlayersRoute: ClubSavedPlayersRoute,
  ClubSettingsRoute: ClubSettingsRoute,
  ClubShortlistRoute: ClubShortlistRoute,
  ClubTrialsRoute: ClubTrialsRoute,
  ClubIndexRoute: ClubIndexRoute,
  ClubClubsClubIdRoute: ClubClubsClubIdRoute,
  ClubMessagesConversationIdRoute: ClubMessagesConversationIdRoute,
  ClubPlayersPlayerIdRoute: ClubPlayersPlayerIdRoute,
  ClubVacanciesNewRoute: ClubVacanciesNewRoute,
  ClubMessagesIndexRoute: ClubMessagesIndexRoute,
  ClubVacanciesIndexRoute: ClubVacanciesIndexRoute,
  ClubVacanciesVacancyIdEditRoute: ClubVacanciesVacancyIdEditRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

interface PlayerRouteChildren {
  PlayerApplicationsRoute: typeof PlayerApplicationsRoute
  PlayerFindClubsRoute: typeof PlayerFindClubsRoute
  PlayerFindPlayersRoute: typeof PlayerFindPlayersRoute
  PlayerProfileRoute: typeof PlayerProfileRoute
  PlayerSavedRoute: typeof PlayerSavedRoute
  PlayerSettingsRoute: typeof PlayerSettingsRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
  PlayerClubsClubIdRoute: typeof PlayerClubsClubIdRoute
  PlayerMessagesConversationIdRoute: typeof PlayerMessagesConversationIdRoute
  PlayerPlayersPlayerIdRoute: typeof PlayerPlayersPlayerIdRoute
  PlayerTrialsInviteIdRoute: typeof PlayerTrialsInviteIdRoute
  PlayerMessagesIndexRoute: typeof PlayerMessagesIndexRoute
  PlayerTrialsIndexRoute: typeof PlayerTrialsIndexRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerApplicationsRoute: PlayerApplicationsRoute,
  PlayerFindClubsRoute: PlayerFindClubsRoute,
  PlayerFindPlayersRoute: PlayerFindPlayersRoute,
  PlayerProfileRoute: PlayerProfileRoute,
  PlayerSavedRoute: PlayerSavedRoute,
  PlayerSettingsRoute: PlayerSettingsRoute,
  PlayerIndexRoute: PlayerIndexRoute,
  PlayerClubsClubIdRoute: PlayerClubsClubIdRoute,
  PlayerMessagesConversationIdRoute: PlayerMessagesConversationIdRoute,
  PlayerPlayersPlayerIdRoute: PlayerPlayersPlayerIdRoute,
  PlayerTrialsInviteIdRoute: PlayerTrialsInviteIdRoute,
  PlayerMessagesIndexRoute: PlayerMessagesIndexRoute,
  PlayerTrialsIndexRoute: PlayerTrialsIndexRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClubRoute: ClubRouteWithChildren,
  CookiesRoute: CookiesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PlayerRoute: PlayerRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WelcomeRoute: WelcomeRoute,
  AdminClubsRoute: AdminClubsRoute,
  AdminConnectionsRoute: AdminConnectionsRoute,
  AdminConversationsRoute: AdminConversationsRoute,
  AdminFounderClubsRoute: AdminFounderClubsRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOwnerStatusRoute: AdminOwnerStatusRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrialsRoute: AdminTrialsRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  ClubsSlugRoute: ClubsSlugRoute,
  JoinClubRoute: JoinClubRoute,
  JoinPlayerRoute: JoinPlayerRoute,
  PlayersSlugRoute: PlayersSlugRoute,
  VacanciesSlugRoute: VacanciesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  JoinIndexRoute: JoinIndexRoute,
  AdminUsersProfileIdRoute: AdminUsersProfileIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  ApiPublicShareImageKindSlugRoute: ApiPublicShareImageKindSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
